// ============================================================================
// PRICING DATA - Extracted from Excel Spreadsheet
// ============================================================================

const pricingData = {
  plans: {
    poolOnly: 410,
    spa: 80,
    waterfall: 15,
    waterFeature: 10,
    soilSampleEngineer: 750,
  },
  excavation: {
    basePricePerSqft: 2700,
    over1000Sqft: 4900,
    additional6InchDepth: 90,
    rbb6: 5,
    rbb12: 6.5,
    rbb18: 7.5,
    rbb24: 8.5,
    rbb30: 9,
    rbb36: 10,
    baseSpa: 200,
    raisedSpa: 350,
    sitePrep: 200,
    backfill: 600,
    gravelPerTon: 2.75,
    dirtHaulPerLoad: 18,
    coverBox: 450,
    travelPerMile: 7,
    misc: 75,
  },
  plumbing: {
    shortStub: 550,
    spaBase: 750,
    poolOverrunPerFt: 25,
    poolOverrunThreshold: 33,
    gasOverrunPerFt: 22,
    gasOverrunThreshold: 25,
    waterFeature1: 3.25,
    waterFeature2: 3,
    waterFeature3: 3.5,
    waterFeature4: 4.5,
    deckJet1: 5.5,
    deckJet2: 7,
    deckJet3: 8.75,
    deckJet4: 5.5,
    deckJet5: 5.5,
    deckJet6: 5.5,
    bubbler1: 5.5,
    bubbler2: 4.5,
    bubbler3: 275,
    wokPot1: 175,
    wokPot2: 300,
    infinityEdge: 10,
    spillwayBase: 2.75,
    spillwayPerFt: 700,
    spaPlumbing: 5,
    twoInchPipe: 5.5,
    twoPointFiveInchPipe: 7,
    threeInchPipe: 8.75,
    infloorPerFt: 10,
    conduitPerFt: 2.75,
    manifold: 175,
    stripForms: 700,
  },
  waterFeatures: {
    // Pricing pulled from Regular pricing.xlsx, Equip tab, column S
    catalog: [
      { id: 'sheer-12', name: '12" Sheer Descent', category: 'Sheer Descents', unitPrice: 760, note: 'Cascading Water Feature' },
      { id: 'sheer-18', name: '18" Sheer Descent', category: 'Sheer Descents', unitPrice: 780, note: 'Cascading Water Feature' },
      { id: 'sheer-2', name: "2' Sheer Descent", category: 'Sheer Descents', unitPrice: 820, note: 'Cascading Water Feature' },
      { id: 'sheer-3', name: "3' Sheer Descent", category: 'Sheer Descents', unitPrice: 880, note: 'Cascading Water Feature' },
      { id: 'sheer-4', name: "4' Sheer Descent", category: 'Sheer Descents', unitPrice: 1000, note: 'Cascading Water Feature' },
      { id: 'sheer-5', name: "5' Sheer Descent (Requires 2nd Pump)", category: 'Sheer Descents', unitPrice: 1120, note: 'Requires second pump' },
      { id: 'sheer-6', name: "6' Sheer Descent (Requires 2nd Pump)", category: 'Sheer Descents', unitPrice: 1300, note: 'Requires second pump' },
      { id: 'deck-jet', name: 'Deck Jet', category: 'Jets', unitPrice: 420 },
      { id: 'laminar-jet', name: 'Laminar Jet', category: 'Jets', unitPrice: 1760 },
      { id: 'wok-water-30', name: '30" Precast Wok - Water Only', category: 'Precast Woks - Water Only', unitPrice: 1920 },
      { id: 'wok-water-32', name: '32" Precast Wok - Water Only', category: 'Precast Woks - Water Only', unitPrice: 2060 },
      { id: 'wok-water-36', name: '36" Precast Wok - Water Only', category: 'Precast Woks - Water Only', unitPrice: 2260, note: 'Add $500 for Copper' },
      { id: 'wok-fire-water-30', name: '30" Precast Wok - Fire & Water', category: 'Precast Woks - Fire & Water', unitPrice: 5060, note: 'Match throw add $588, auto add $2134, add $500 for copper' },
      { id: 'wok-fire-water-36', name: '36" Precast Wok - Fire & Water', category: 'Precast Woks - Fire & Water', unitPrice: 6020, note: 'Match throw add $588, auto add $2134, add $500 for copper' },
      { id: 'wok-fire-30', name: '30" Precast Wok - Fire Only', category: 'Precast Woks - Fire Only', unitPrice: 1760, note: 'Match throw add $588, auto add $2134, add $500 for copper' },
      { id: 'wok-fire-36', name: '36" Precast Wok - Fire Only', category: 'Precast Woks - Fire Only', unitPrice: 2100, note: 'Match throw add $588, auto add $2134, add $500 for copper' },
      { id: 'led-bubbler', name: 'LED Bubbler (with light)', category: 'Bubblers & Lighting', unitPrice: 1380, note: 'Includes bubbler and light; add matching light run + water feature run' },
    ],
  },
    electrical: {
      baseElectrical: 1650,
      overrunPerFt: 18,
      overrunThreshold: 65,
      spaElectrical: 100,
      lightRunBase: 100,
      lightRunOverrunPerFt: 450,
      lightRunThreshold: 65,
      baseGas: 1500,
      gasPer10Ft: 11,
      subPanel: 7,
      heatPumpElectrical: 3,
    },
  steel: {
    poolBase: 25,
    spaBase: 100,
    stepsPerLnft: 0,
    tanningShelf: 100,
    over700Sqft: 450,
    rbb6PerLnft: 150,
    rbb12PerLnft: 8,
    rbb18PerLnft: 3,
    rbb24PerLnft: 4,
    rbb30PerLnft: 5,
    rbb36PerLnft: 6,
    doubleCurtainPerLnft: 7,
    automaticCover: 7,
  },
  shotcrete: {
    labor: {
      poolBase: 90,
      spaBase: 90,
      per100SqftOver500: 250,
      tanningShelf: 250,
      stepsPerLnft: 500,
      raisedBondBeam6: 1000,
      raisedBondBeam12: 7,
      raisedBondBeam18: 0,
      raisedBondBeam24: 0,
      raisedBondBeam30: 0,
      raisedBondBeam36: 0,
      raisedSpa: 228,
      spillwayPerLnft: 125,
    },
    material: {
      poolPerSqft: 228,
      spaPerSqft: 75,
      tanningShelfPerSqft: 1,
      stepsPerLnft: 6,
      rbb6PerLnft: 0,
      rbb12PerLnft: 0,
      rbb18PerLnft: 0,
      rbb24PerLnft: 0,
      rbb30PerLnft: 0,
      rbb36PerLnft: 0,
      raisedSpaPerSqft: 0,
      spillwayPerLnft: 0,
    },
  },
  tileCoping: {
    tile: {
      labor: {
        level1: 10,
        level2: 10,
        level3: 10,
        stepTrim: 10,
      },
      material: {
        level1Included: true,
        level2Upgrade: 20,
        level3Upgrade: 50,
      },
    },
    coping: {
      cantilever: 7,
      flagstone: 15,
      pavers: 12,
      travertineLevel1: 12,
      travertineLevel2: 12,
      concrete: 16.5,
    },
    decking: {
      labor: {
        pavers: 8,
        travertine: 8,
        concrete: 16.5,
        concreteSteps: 27,
      },
      material: {
        pavers: 7,
        travertineLevel1: 7.5,
        travertineLevel2: 9.75,
        concrete: 7,
        concreteSteps: 7.5,
      },
    },
  },
  equipment: {
    pumps: [
      { name: 'Jandy 1.65HP Variable Pump', model: 'VS-1.65HP', price: 2310 },
      { name: 'Jandy 1.85HP Variable Pump', model: 'VS-1.85HP', price: 2540 },
      { name: 'Jandy 2.7HP Variable Pump', model: 'VS-2.7HP', price: 3110 },
      { name: 'Jandy 1.0HP Single Speed Pump', model: 'SS-1.0HP', price: 1900 },
      { name: 'Jandy 2.0HP Single Speed Pump', model: 'SS-2.0HP', price: 2060 },
    ],
    filters: [
      { name: '200 SQFT Cartridge Filter', sqft: 200, price: 1103.57 },
      { name: '340 SQFT Cartridge Filter', sqft: 340, price: 1618.57 },
      { name: '460 SQFT Cartridge Filter', sqft: 460, price: 1677.43 },
      { name: '580 SQFT Cartridge Filter', sqft: 580, price: 2133.57 },
      { name: '4.9 SQFT Sand Filter', sqft: 0, price: 1115.2 },
      { name: '60 SQFT DE Filter', sqft: 60, price: 1224.37 },
    ],
    cleaners: [
      { name: 'Polaris Epic IQ', price: 1540 },
      { name: 'Polaris Alpha IQ', price: 2000 },
      { name: 'Polaris 360 Standard', price: 1618.57 },
      { name: 'Polaris 360 Black', price: 1677.43 },
      { name: 'Polaris 280 w/ Booster', price: 2133.57 },
      { name: 'No Cleaner', price: 0 },
    ],
    heaters: [
      { name: 'Jandy 400K BTU - VersaFlo', btu: 400000, price: 4710, isVersaFlo: true },
      { name: 'Jandy LXI 250K BTU', btu: 250000, price: 1885, isVersaFlo: false },
      { name: 'Jandy JXI 400K - No Bypass', btu: 400000, price: 2308, isVersaFlo: false },
      { name: 'Jandy JXI 400K - w/ Bypass', btu: 400000, price: 2475, isVersaFlo: false },
      { name: 'Heat Pump', btu: 0, price: 0, isVersaFlo: false },
    ],
    lights: {
      nicheLightPrice: 860, // 24 Watt - Jandy Nicheless LED (S column)
      spaLightAddon: 0,
      additionalLightPrice: 860,
      catalog: [],
    },
    automation: [
      { name: 'iAqualink w/ Rev. R', price: 1720, hasChemistry: false },
      { name: 'iAqualink Controller - New Install', price: 1720, hasChemistry: false },
      { name: 'iAqualink P4 Bundle', price: 0, hasChemistry: false },
      { name: 'iAqualink PS4 Bundle', price: 0, hasChemistry: false },
      { name: 'iAqualink RS Upgrade', price: 0, hasChemistry: false },
      { name: 'Jandy TCX Controler (1 JVA, Lights and Heater Control)', price: 1217.78, hasChemistry: false },
    ],
    automationZoneAddon: 365, // Per additional zone
    saltSystem: [
      { name: 'Jandy AquaPure 1400', model: 'AquaPure', price: 0 },
      { name: 'Jandy Tru-Clear', model: 'TruClear', price: 1150 },
      { name: 'Salt/mineral System - Fusion Soft', model: 'FusionSoft', price: 1430 },
      { name: 'No Salt System', model: 'None', price: 0 },
    ],
    blanketReel: 0,
    solarBlanket: 0,
    autoFill: 0,
    handrail: 0,
    startupChemicals: 0,
    baseWhiteGoods: 1046.1,
  },
  interiorFinish: {
    labor: {
      plasterBase: 5.5,
      plasterPer100SqftOver500: 0,
      pebbleBase: 6.3,
      pebblePer100SqftOver500: 0,
      quartzBase: 7.9,
      quartzPer100SqftOver500: 0,
      polishedBase: 6.75,
      polishedPer100SqftOver500: 0,
      tileBase: 9.25,
      tilePer100SqftOver500: 0,
      spa: 850,
    },
    material: {
      plaster: 1.5,
      pebbleTec: 6.3,
      pebbleSheen: 6.75,
      pebbleFina: 7.75,
      miniPebble: 6.3,
      beadcrete: 6.75,
      quartzScapes: 7.9,
      hydrazzo: 9.25,
      tile: 9.25,
      spaFinish: 1150,
      ivoryQuartz: 5.5,
      pebbleTecL1: 6.3,
      pebbleTecL2: 7.9,
      pebbleTecL3: 8.85,
      pebbleSheenL1: 6.75,
      pebbleSheenL2: 7.85,
      pebbleSheenL3: 9.25,
      pebbleFinaL1: 7.75,
      pebbleFinaL2: 10,
      pebbleBrilliance: 17,
      pebbleBreeze: 23,
      pebbleEssence: 17.5,
    },
    waterTruck: {
      base: 490,
      per1000Gallons: 70,
    },
  },
  cleanup: {
    basePool: 700,
    spa: 100,
    per100SqftOver500: 0.5,
    dumpRuns: 56,
  },
  fiberglass: {
    small: 12192,
    medium: 15120,
    large: 18228,
    crystite: 16632,
    spaSmall: 8727,
    spaMedium: 10242,
    spaLarge: 13857,
    spillover: 1000,
    crane: 2500,
    models: [
      { name: 'Caeser', size: 'small', price: 11325, perimeter: 48 },
      { name: 'Chateau & Gayla 12', size: 'small', price: 14825, perimeter: 70 },
      { name: 'Gayla 12/Freeport', size: 'small', price: 14375, perimeter: 64 },
      { name: 'Lotus 12/Bermuda', size: 'small', price: 15375, perimeter: 73 },
      { name: 'Santorini & Bliss 12', size: 'small', price: 12825, perimeter: 59 },
      { name: 'Belvedere', size: 'medium', price: 22801, perimeter: 84 },
      { name: 'Martinique Grand', size: 'medium', price: 23825, perimeter: 92 },
      { name: 'Noveau 14', size: 'medium', price: 23625, perimeter: 83 },
      { name: 'Lotus 14', size: 'medium', price: 20650, perimeter: 74 },
      { name: 'Renaissance 14', size: 'medium', price: 23625, perimeter: 81 },
      { name: 'Sovereign & Gayla 14', size: 'medium', price: 21275, perimeter: 90 },
      { name: 'Belvedere/Olympia 14', size: 'medium', price: 24100, perimeter: 85 },
      { name: 'Aristocrat', size: 'large', price: 25075, perimeter: 104 },
      { name: 'Lotus XL', size: 'large', price: 26100, perimeter: 101 },
      { name: 'Elysium Grand', size: 'large', price: 25600, perimeter: 114 },
      { name: 'Grand Palace', size: 'large', price: 30000, perimeter: 137 },
      { name: 'Imperial', size: 'large', price: 21700, perimeter: 94 },
      { name: 'Gayla 16', size: 'large', price: 24000, perimeter: 96 },
      { name: 'Oasis 16', size: 'large', price: 23300, perimeter: 87 },
      { name: 'Gayla XDL', size: 'large', price: 27725, perimeter: 83 },
      { name: 'Versailles', size: 'large', price: 30500, perimeter: 108 },
      { name: 'Villa Reale', size: 'large', price: 29600, perimeter: 107 },
    ],
    spas: [
      { name: 'Meridian', price: 4794 },
      { name: 'Mystic', price: 4575 },
      { name: 'Regal', price: 5000 },
      { name: 'Royal', price: 5000 },
    ],
  },
  misc: {
    layout: {
      poolOnly: 50,
      spa: 15,
      siltFencing: 500,
    },
    permit: {
      poolOnly: 850,
      spa: 150,
      permitRunner: 75,
    },
    equipmentSet: {
      base: 750,
      spa: 100,
      automation: 200,
      heatPump: 100,
    },
    drainage: {
      downspoutPerFt: 11,
      deckDrainPerFt: 15,
      frenchDrainPerFt: 12,
      boxDrainPerFt: 18,
    },
  },
  masonry: {
    columnBase: 500,
    raisedSpaFacing: {
      tile: 350,
      ledgestone: 400,
      stackedStone: 450,
    },
    rbbFacing: {
      tile: 300,
      panelLedge: 350,
      stackedStone: 400,
    },
  },
};

export default pricingData;
