// ============================================================================
// PRICING DATA - Extracted from Excel Spreadsheet
// ============================================================================

const pricingData = {
  plans: {
    poolOnly: 410,
    spa: 80,
    waterfall: 15,
    waterFeature: 10,
    soilSampleEngineer: 750,
  },
  excavation: {
    basePricePerSqft: 2700,
    over1000Sqft: 4900,
    additional6InchDepth: 90,
    rbb6: 5,
    rbb12: 6.5,
    rbb18: 7.5,
    rbb24: 8.5,
    rbb30: 9,
    rbb36: 10,
    baseSpa: 200,
    raisedSpa: 350,
    sitePrep: 200,
    backfill: 600,
    gravelPerTon: 1,
    dirtHaulPerLoad: 18,
    coverBox: 450,
    travelPerMile: 7,
    misc: 75,
  },
  plumbing: {
    shortStub: 550,
    spaBase: 750,
    poolOverrunPerFt: 25,
    poolOverrunThreshold: 33,
    gasOverrunPerFt: 22,
    gasOverrunThreshold: 30,
    waterFeature1: 3.25,
    waterFeature2: 3,
    waterFeature3: 3.5,
    waterFeature4: 4.5,
    deckJet1: 5.5,
    deckJet2: 7,
    deckJet3: 8.75,
    deckJet4: 5.5,
    deckJet5: 5.5,
    deckJet6: 5.5,
    bubbler1: 5.5,
    bubbler2: 4.5,
    bubbler3: 275,
    wokPot1: 175,
    wokPot2: 300,
    infinityEdge: 10,
    spillwayBase: 2.75,
    spillwayPerFt: 700,
    spaPlumbing: 5,
  },
  electrical: {
    baseElectrical: 1650,
    overrunPerFt: 18,
    overrunThreshold: 100,
    spaElectrical: 100,
    lightRunBase: 255,
    lightRunOverrunPerFt: 450,
    lightRunThreshold: 150,
    gasPer10Ft: 250,
    subPanel: 7,
    heatPumpElectrical: 3,
  },
  steel: {
    poolBase: 25,
    spaBase: 100,
    stepsPerLnft: 0,
    tanningShelf: 100,
    over700Sqft: 450,
    rbb6PerLnft: 150,
    rbb12PerLnft: 8,
    rbb18PerLnft: 3,
    rbb24PerLnft: 4,
    rbb30PerLnft: 5,
    rbb36PerLnft: 6,
    doubleCurtainPerLnft: 7,
    automaticCover: 7,
  },
  shotcrete: {
    labor: {
      poolBase: 90,
      spaBase: 90,
      per100SqftOver500: 250,
      tanningShelf: 250,
      stepsPerLnft: 500,
      raisedBondBeam6: 1000,
      raisedBondBeam12: 7,
      raisedBondBeam18: 0,
      raisedBondBeam24: 0,
      raisedBondBeam30: 0,
      raisedBondBeam36: 0,
      raisedSpa: 228,
      spillwayPerLnft: 125,
    },
    material: {
      poolPerSqft: 32,
      spaPerSqft: 75,
      tanningShelfPerSqft: 1,
      stepsPerLnft: 6,
      rbb6PerLnft: 0,
      rbb12PerLnft: 0,
      rbb18PerLnft: 0,
      rbb24PerLnft: 0,
      rbb30PerLnft: 0,
      rbb36PerLnft: 0,
      raisedSpaPerSqft: 0,
      spillwayPerLnft: 0,
    },
  },
  tileCoping: {
    tile: {
      labor: {
        level1: 7,
        level2: 20,
        level3: 50,
        stepTrim: 10,
      },
      material: {
        level1Included: true,
        level2Upgrade: 7,
        level3Upgrade: 20,
      },
    },
    coping: {
      cantilever: 7,
      flagstone: 0,
      pavers: 0,
      travertineLevel1: 0,
      travertineLevel2: 0,
      concrete: 12,
    },
    decking: {
      labor: {
        pavers: 8,
        travertine: 15,
        concrete: 16.5,
        concreteSteps: 600,
      },
      material: {
        pavers: 0,
        travertineLevel1: 9,
        travertineLevel2: 7,
        concrete: 11,
        concreteSteps: 7.5,
      },
    },
  },
  equipment: {
    pumps: [
      { name: 'Jandy 2.7HP Variable Pump', model: 'VS-2.7HP', price: 2310 },
      { name: 'Jandy 1.65HP Variable Pump', model: 'VS-1.65HP', price: 2540 },
      { name: 'Jandy VS FloPro', model: 'FloPro', price: 3110 },
      { name: 'Pentair IntelliFlo3 VSF', model: 'IntelliFlo3', price: 1900 },
      { name: 'Pentair SuperFlo VS', model: 'SuperFlo', price: 2060 },
    ],
    filters: [
      { name: '580 SQFT Cartridge Filter', sqft: 580, price: 1104 },
      { name: '420 SQFT Cartridge Filter', sqft: 420, price: 1619 },
      { name: '325 SQFT Cartridge Filter', sqft: 325, price: 1677 },
      { name: '27" Sand Filter', sqft: 0, price: 2134 },
      { name: '24" Sand Filter', sqft: 0, price: 1115 },
      { name: '22" Sand Filter', sqft: 0, price: 1224 },
    ],
    cleaners: [
      { name: 'Polaris Alpha IQ', price: 2000 },
      { name: 'Polaris 380', price: 1540 },
      { name: 'No Cleaner', price: 0 },
    ],
    heaters: [
      { name: 'Jandy 400K BTU - VersaFlo', btu: 400000, price: 4710, isVersaFlo: true },
      { name: 'Jandy 260K BTU - JXI Heater', btu: 260000, price: 7394, isVersaFlo: false },
      { name: 'RayPak 266K BTU - Digital', btu: 266000, price: 4710, isVersaFlo: false },
      { name: 'Heat Pump', btu: 0, price: 0, isVersaFlo: false },
    ],
    lights: {
      nicheLightPrice: 755,
      spaLightAddon: 1025,
      additionalLightPrice: 860,
    },
    automation: [
      { name: 'iAquaLink - Pool Only', price: 1218, hasChemistry: false },
      { name: 'iAquaLink - Pool & Spa', price: 1238, hasChemistry: false },
      { name: 'iAquaLink - Pool Only w/ Chemistry', price: 1508, hasChemistry: true },
      { name: 'iAquaLink - Pool & Spa w/ Chemistry', price: 1363, hasChemistry: true },
      { name: 'PDA - Pool Only', price: 1673, hasChemistry: false },
      { name: 'PDA - Pool & Spa', price: 2078, hasChemistry: false },
      { name: 'ScreenLogic', price: 3378, hasChemistry: false },
      { name: 'Pentair EasyTouch - Pool Only', price: 1645, hasChemistry: false },
      { name: 'Pentair EasyTouch - Pool & Spa', price: 1430, hasChemistry: false },
    ],
    automationZoneAddon: 365, // Per additional zone
    saltSystem: [
      { name: 'Jandy AquaPure 1400', model: 'AquaPure', price: 0 },
      { name: 'Pentair IC40', model: 'IC40', price: 810 },
      { name: 'No Salt System', model: 'None', price: 0 },
    ],
    blanketReel: 0,
    solarBlanket: 0,
    autoFill: 0,
    handrail: 0,
    startupChemicals: 0,
  },
  interiorFinish: {
    labor: {
      plasterBase: 2,
      plasterPer100SqftOver500: 0,
      pebbleBase: 5.5,
      pebblePer100SqftOver500: 6.3,
      quartzBase: 7.9,
      quartzPer100SqftOver500: 8.85,
      polishedBase: 6.75,
      polishedPer100SqftOver500: 7.85,
      tileBase: 9.25,
      tilePer100SqftOver500: 7.75,
      spa: 850,
    },
    material: {
      plaster: 1.5,
      pebbleTec: 13.5,
      pebbleSheen: 14.5,
      pebbleFina: 15.5,
      miniPebble: 14,
      beadcrete: 12.5,
      quartzScapes: 15.75,
      hydrazzo: 18,
      tile: 25,
      spaFinish: 1050,
    },
    waterTruck: {
      base: 1050,
      per1000Gallons: 60,
    },
  },
  cleanup: {
    basePool: 700,
    spa: 100,
    per100SqftOver500: 100,
    dumpRuns: 56,
  },
  fiberglass: {
    small: 12192,
    medium: 15120,
    large: 18228,
    crystite: 16632,
    spaSmall: 8727,
    spaMedium: 10242,
    spaLarge: 13857,
    spillover: 1000,
    crane: 2500,
  },
  misc: {
    layout: {
      poolOnly: 50,
      spa: 15,
      siltFencing: 500,
    },
    permit: {
      poolOnly: 850,
      spa: 150,
      permitRunner: 75,
    },
    equipmentSet: {
      base: 800,
      spa: 100,
      automation: 75,
      heatPump: 100,
    },
    drainage: {
      downspoutPerFt: 11,
      deckDrainPerFt: 15,
      frenchDrainPerFt: 12,
      boxDrainPerFt: 18,
    },
  },
  masonry: {
    columnBase: 500,
    raisedSpaFacing: {
      tile: 350,
      ledgestone: 400,
      stackedStone: 450,
    },
    rbbFacing: {
      tile: 300,
      panelLedge: 350,
      stackedStone: 400,
    },
  },
};

export default pricingData;
